name:           The Final Countdown
nickname:       jQuery.countdown
plugin_version: 2.2.0
baseurl:        https://github.com/x20mar/marks-retiring
highlight:      true
markdown:       kramdown
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
collections:
  examples:
    output: true
exclude:
  - node_modules/
