name:           Mark is finally retiring
nickname:       Mark's Retiring
plugin_version: 2.2.0
baseurl:        https://omara.li/marks-retiring
highlight:      true
markdown:       kramdown
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
collections:
  examples:
    output: true
exclude:
  - node_modules/
